In [7]:
# Directories creation for GTZAN
genres = 'blues jazz classical country disco pop hiphop metal reggae rock'
genres = genres.split()
for g in genres:
  path_audio = os.path.join('Datasets/GTZAN_GENRE_COLLECTION/audio3sec',f'{g}')
  os.makedirs(path_audio)

In [ ]:
'''
This notebook is oriented to the creation of an pandas dataframe builded from GTZAN Music Genre Dataset:
This features are: cqt, rmse, energy, mfccs, chromagram and spectral contrast
This notebook is currently in development phase, so contains a considerably quantity of test code
'''

In [2]:
import tensorflow as tf
import pandas as pd
from pathlib import Path
import librosa, librosa.display
import matplotlib.pyplot as plt
import numpy as np
import gc
import os
import pydub
import tensorflow_datasets as tfds

# tfds.load('gtzan', split='train', shuffle_files=True)

# print(tfds)

genres = 'blues jazz classical country disco pop hiphop metal reggae rock'
genres = genres.split()

In [1]:
# GTZAN --- DATA AUGMENTATION
genres = 'blues jazz classical country disco pop hiphop metal reggae rock'
genres = genres.split()
for g in genres:
    print(f"{g}")
    songIndex = -1
    for filename in os.listdir(os.path.join('Datasets/GTZAN_GENRE_COLLECTION/genres',f"{g}")):
        song  =  os.path.join(r"C:\Users\alvar\github\TFGa\MyTFG\python\Datasets\GTZAN_GENRE_COLLECTION\genres", f'{g}', f'{filename}')
        print(song)
        songIndex = songIndex + 1
        for sliceIndex in range(0,10):
            t1 = 3*(sliceIndex)*1000
            t2 = 3*(sliceIndex+1)*1000
            newAudio = pydub.AudioSegment.from_file(song)
            new = newAudio[t1:t2]
            new_filename = g + "0" + str(songIndex) + str(sliceIndex)
            print(new_filename)
            song_out = os.path.join(r"C:\Users\alvar\github\TFGa\MyTFG\python\Datasets\GTZAN_GENRE_COLLECTION\audio3sec", f'{g}', f'{new_filename}')
            new.export(song_out, format="au")

NameError: name 'genres' is not defined

In [1]:

"""
This block is aim to read original GTZAN Dataset
"""

# Reading Audio Data from GTZAN

print('iniciando...')

audios_blues = [
    librosa.load(p)[0] for p in Path().glob('Datasets/GTZAN_GENRE_COLLECTION/genres/blues/blues.000*.au')
]

audios_classical = [
    librosa.load(p)[0] for p in Path().glob('Datasets/GTZAN_GENRE_COLLECTION/genres/classical/classical.000*.au')
]

audios_country = [
    librosa.load(p)[0] for p in Path().glob('Datasets/GTZAN_GENRE_COLLECTION/genres/country/country.000*.au')
]

audios_disco = [
    librosa.load(p)[0] for p in Path().glob('Datasets/GTZAN_GENRE_COLLECTION/genres/disco/disco.000*.au')
]

audios_hiphop = [
    librosa.load(p)[0] for p in Path().glob('Datasets/GTZAN_GENRE_COLLECTION/genres/hiphop/hiphop.000*.au')
]

audios_jazz = [
    librosa.load(p)[0] for p in Path().glob('Datasets/GTZAN_GENRE_COLLECTION/genres/jazz/jazz.000*.au')
]

audios_metal = [
    librosa.load(p)[0] for p in Path().glob('Datasets/GTZAN_GENRE_COLLECTION/genres/metal/metal.000*.au')
]

audios_pop = [
    librosa.load(p)[0] for p in Path().glob('Datasets/GTZAN_GENRE_COLLECTION/genres/pop/pop.000*.au')
]

audios_reggae = [
    librosa.load(p)[0] for p in Path().glob('Datasets/GTZAN_GENRE_COLLECTION/genres/reggae/reggae.000*.au')
]

audios_rock = [
    librosa.load(p)[0] for p in Path().glob('Datasets/GTZAN_GENRE_COLLECTION/genres/rock/rock.000*.au')
]


print('Ha salio bien')

iniciando...
Ha salio bien


In [16]:

"""
This block is aim to read slice in 10 GTZAN Dataset
"""

# Reading Audio Data

print('iniciando...')

audios_blues = [
        librosa.load(p)[0] for p in Path().glob('Datasets/GTZAN_GENRE_COLLECTION/audio3sec/blues/blues0*')
]

audios_classical = [
    librosa.load(p)[0] for p in Path().glob('Datasets/GTZAN_GENRE_COLLECTION/audio3sec/classical/classical0*')
]

audios_country = [
    librosa.load(p)[0] for p in Path().glob('Datasets/GTZAN_GENRE_COLLECTION/audio3sec/country/country0*')
]

audios_disco = [
    librosa.load(p)[0] for p in Path().glob('Datasets/GTZAN_GENRE_COLLECTION/audio3sec/disco/disco0*')
]

audios_hiphop = [
    librosa.load(p)[0] for p in Path().glob('Datasets/GTZAN_GENRE_COLLECTION/audio3sec/hiphop/hiphop0*')
]

audios_jazz = [
    librosa.load(p)[0] for p in Path().glob('Datasets/GTZAN_GENRE_COLLECTION/audio3sec/jazz/jazz0*')
]

audios_metal = [
    librosa.load(p)[0] for p in Path().glob('Datasets/GTZAN_GENRE_COLLECTION/audio3sec/metal/metal0*')
]

audios_pop = [
    librosa.load(p)[0] for p in Path().glob('Datasets/GTZAN_GENRE_COLLECTION/audio3sec/pop/pop0*')
]

audios_reggae = [
    librosa.load(p)[0] for p in Path().glob('Datasets/GTZAN_GENRE_COLLECTION/audio3sec/reggae/reggae0*')
]

audios_rock = [
    librosa.load(p)[0] for p in Path().glob('Datasets/GTZAN_GENRE_COLLECTION/audio3sec/rock/rock0*')
]

print('Ha salio bien')


iniciando...
Ha salio bien


In [22]:
for filename in glob.glob('Datasets/ismir04_genre/audio/evaluation/classical/**/*.mp3', recursive=True):
    new = pydub.AudioSegment.from_file(filename)
    song_out  =  os.path.join(r"C:\Users\alvar\github\gitTfgPy\TFGNotebooks\Datasets\ismir04_genre\audio\evaluation", f'{g}', f'')
    new.export(song_out, format="au")

Datasets/ismir04_genre/audio/evaluation/classical\american_baroque\dances_and_suites_of_rameau_an\1-overture_suite_from_les_fetes.mp3
Datasets/ismir04_genre/audio/evaluation/classical\american_baroque\dances_and_suites_of_rameau_an\2-air_gai_suite_from_les_fetes.mp3
Datasets/ismir04_genre/audio/evaluation/classical\american_baroque\dances_and_suites_of_rameau_an\20-la_linote_efarouchee_xiveme_o.mp3
Datasets/ismir04_genre/audio/evaluation/classical\american_baroque\dances_and_suites_of_rameau_an\25-le_petit_rien_xiveme_ordre_(c.mp3
Datasets/ismir04_genre/audio/evaluation/classical\american_baroque\dances_and_suites_of_rameau_an\29-menuets_1_2_suite_in_d_from.mp3
Datasets/ismir04_genre/audio/evaluation/classical\american_baroque\dances_and_suites_of_rameau_an\5-gavottes_suite_from_les_fetes.mp3
Datasets/ismir04_genre/audio/evaluation/classical\american_baroque\dances_and_suites_of_rameau_an\6-rigaudon_suite_from_les_fetes.mp3
Datasets/ismir04_genre/audio/evaluation/classical\american_bar

KeyboardInterrupt: 

In [5]:
# Audios subfolders extraction for ISMIR 04
import glob
genres = 'classical electronic jazz metal pop punk rock world'
genres = genres.split()
for g in genres:
    print(f"{g}")
    songIndex = -1
    for filename in glob.glob(os.path.join('Datasets/ismir04_genre/audio/evaluation',f"{g}", '**/*.mp3'), recursive=True):
        print(filename)
        t1 = 3*1000
        t2 = 3*(2)*1000
        songIndex = songIndex + 1
        newAudio = pydub.AudioSegment.from_file(filename)
        new = newAudio[t1:t2]
        new_filename = g + "0" + str(songIndex) + ".au"
        song_out  =  os.path.join(r"C:\Users\alvar\github\gitTfgPy\TFGNotebooks\Datasets\ismir04_genre\audio\evaluation", f'{g}', f'{new_filename}')
        new.export(song_out, format="au")

classical
Datasets/ismir04_genre/audio/evaluation\classical\american_baroque\dances_and_suites_of_rameau_an\1-overture_suite_from_les_fetes.mp3
Datasets/ismir04_genre/audio/evaluation\classical\american_baroque\dances_and_suites_of_rameau_an\2-air_gai_suite_from_les_fetes.mp3
Datasets/ismir04_genre/audio/evaluation\classical\american_baroque\dances_and_suites_of_rameau_an\20-la_linote_efarouchee_xiveme_o.mp3
Datasets/ismir04_genre/audio/evaluation\classical\american_baroque\dances_and_suites_of_rameau_an\25-le_petit_rien_xiveme_ordre_(c.mp3
Datasets/ismir04_genre/audio/evaluation\classical\american_baroque\dances_and_suites_of_rameau_an\29-menuets_1_2_suite_in_d_from.mp3
Datasets/ismir04_genre/audio/evaluation\classical\american_baroque\dances_and_suites_of_rameau_an\5-gavottes_suite_from_les_fetes.mp3
Datasets/ismir04_genre/audio/evaluation\classical\american_baroque\dances_and_suites_of_rameau_an\6-rigaudon_suite_from_les_fetes.mp3
Datasets/ismir04_genre/audio/evaluation\classical\am

In [6]:
"""
This block is aim to read original ISMIR04 Dataset
"""

# Reading Audio Data from ISMIR04

print('iniciando...')

audios_classical = [
    librosa.load(p)[0] for p in Path().glob('Datasets/ismir04_genre/audio/evaluation/classical/classical0*')
]

audios_electronic = [
    librosa.load(p)[0] for p in Path().glob('Datasets/ismir04_genre/audio/evaluation/electronic/electronic0*')
]

audios_jazz = [
    librosa.load(p)[0] for p in Path().glob('Datasets/ismir04_genre/audio/evaluation/jazz/jazz0*')
]

audios_metal = [
    librosa.load(p)[0] for p in Path().glob('Datasets/ismir04_genre/audio/evaluation/metal/metal0*')
]

audios_pop = [
    librosa.load(p)[0] for p in Path().glob('Datasets/ismir04_genre/audio/evaluation/pop/pop0*')
]

audios_punk = [
    librosa.load(p)[0] for p in Path().glob('Datasets/ismir04_genre/audio/evaluation/punk/punk0*')
]

audios_rock = [
    librosa.load(p)[0] for p in Path().glob('Datasets/ismir04_genre/audio/evaluation/rock/rock0*')
]

audios_world = [
    librosa.load(p)[0] for p in Path().glob('Datasets/ismir04_genre/audio/evaluation/world/world0*')
]

print('Ha salio bien')

iniciando...
Ha salio bien


In [7]:
# Funtions to extracting features 

import sklearn
import librosa

class FeaturesExtractor():
    """
    Class that contains several methods to extract means audio features from an audioArray
    If user dont use specific parameters class use default values
    This class make use of sklean and librosa packages
    
    feature_to_extract = possible values = "mean" or "var"
    """
    
    def __init__(self, hop_length=1024, frame_length=2048, sr=22050, fmin=36, n_bins= 72, lag_seconds=4, feature_to_extract="mean"):
        self.hop_length = hop_length
        self.frame_length = frame_length
        self.sr = sr
        self.fmin = fmin
        self.n_bins = n_bins
        self.lag_seconds = lag_seconds
        self.feature_to_extract = feature_to_extract
    
    def get_short_time_energy(self, audio_array, sr=None, hop_length=None, frame_length=None):
        if sr is None: sr=self.sr
        if hop_length is None: hop_length=self.hop_length
        if frame_length is None: frame_length=self.frame_length
        
        librosa.get_duration(audio_array, sr)
        energy = np.array([
            sum(abs(audio_array[i:i+frame_length]**2))
            for i in range(0, len(audio_array), hop_length)
        ])
        
        if self.feature_to_extract is "mean": return energy.mean(axis=0)
        elif self.feature_to_extract is "var": return energy.var()
        else: return energy

    def get_rmse(self, audio_array, sr=None, hop_length=None, frame_length=None):
        if sr is None: sr=self.sr
        if hop_length is None: hop_length=self.hop_length
        if frame_length is None: frame_length=self.frame_length
        
        rmse = librosa.feature.rms(audio_array, frame_length=frame_length, hop_length=hop_length, center=True)
        rmse = rmse[0]
        if self.feature_to_extract is "mean": return rmse.mean(axis=0)
        elif self.feature_to_extract is "var": return rmse.var()
        else: return rmse


    def get_zcr(self, audio_array):
#       we add a little constant for avoid silence near 0
        zero_crossings = librosa.zero_crossings(audio_array + 0.0001)
        zero_crossings = sum(zero_crossings)
        return zero_crossings
#         return zero_crossings.mean()

    def get_mfccs_means(self, audio_array, sr=None, number_mfccs=13):
        if sr is None: sr=self.sr
            
        mfccs = librosa.feature.mfcc(audio_array, sr, n_mfcc=number_mfccs)
        mfccs_means = np.arange(number_mfccs)
        for i in  range(0, len(mfccs)):
            if self.feature_to_extract is "mean": mfccs_means[i] = mfccs[i].mean(axis=0).mean()
            elif self.feature_to_extract is "var": mfccs_means[i] = mfccs[i].var()
            else: mfccs_means[i] = mfccs[i].mean(axis=0).mean()
            
        
        return mfccs_means
    
#         mfccs = sklearn.preprocessing.scale(mfccs, axis=1)
#         print()
#         print (mfccs.mean(axis=1))
#         print (mfccs.var(axis=1))
#         librosa.display.specshow(mfccs, sr=sr, x_axis='time')
    
    def get_cqt(self, audio_array, sr=None, hop_length=None, fmin=None, n_bins=None):
        if sr is None: sr=self.sr
        if hop_length is None: hop_length=self.hop_length
        if fmin is None: fmin=self.fmin
        if n_bins is None: n_bins=self.n_bins
        
        C = librosa.cqt(audio_array, sr=sr, fmin=fmin, n_bins=n_bins, hop_length=hop_length)
#         return C
        if self.feature_to_extract is "mean": feature = C.mean(axis=0).mean(axis=0)
        elif self.feature_to_extract is "var": feature = C.var()
        else: feature = C.mean(axis=0).mean(axis=0)
        return abs(feature)
        
    def get_chromagram(self, audio_array, sr=None, hop_length=None):
        if sr is None: sr=self.sr
        if hop_length is None: hop_length=self.hop_length
            
        chromagram = librosa.feature.chroma_cens(audio_array, sr=sr, hop_length=hop_length)
#         return chromagram
        if self.feature_to_extract is "mean": feature = chromagram.mean(axis=0).mean(axis=0)
        elif self.feature_to_extract is "var": feature = chromagram.var()
        else: feature = chromagram.mean(axis=0).mean(axis=0)
        return feature

    def get_spectral_contrast(self, audio_array, sr=None):
        if sr is None: sr=self.sr
            
        spectral_contrast = librosa.feature.spectral_contrast(audio_array, sr=self.sr)
#         return spectral_contrast
        if self.feature_to_extract is "mean": feature = spectral_contrast.mean(axis=0).mean(axis=0)
        elif self.feature_to_extract is "var": feature = spectral_contrast.var()
        else: feature = spectral_contrast.mean(axis=0).mean(axis=0)
        return feature

    def get_autocorrelation(self, audio_array, sr=None, hop_length=None, lag_seconds=None):
        if sr is None: sr=self.sr
        if hop_length is None: hop_length=self.hop_length
        if lag_seconds is None: lag_seconds=self.lag_seconds
        
        max_size = lag_seconds * sr / hop_length
        autocorrelation = librosa.autocorrelate(audio_array, max_size)
        
        if self.feature_to_extract is "mean": feature = autocorrelation.mean(axis=0)
        elif self.feature_to_extract is "var": feature = autocorrelation.var()
        else: feature = autocorrelation.mean(axis=0)
        return feature

    # Function that obtain Short Time Fourier Transform from an audio samples array
    def get_stft(self, audio_array, hop_length=None, frame_length=None):
        if hop_length is None: hop_length=self.hop_length
        if frame_length is None: frame_length=self.frame_length
            
        stft = librosa.stft(audio_array, n_fft=frame_length, hop_length=hop_length)
        
        if self.feature_to_extract is "mean": feature = stft.mean(axis=0).mean(axis=0)
        elif self.feature_to_extract is "var": feature = stft.var()
        else: feature = stft.mean(axis=0).mean(axis=0)
        return abs(feature)
    
    def get_rolloff(self, audio_array, sr=None):
        if sr is None: sr=self.sr
        
        spectral_rolloff = librosa.feature.spectral_rolloff(audio_array+0.01, sr=sr)
        
        if self.feature_to_extract is "mean": feature = spectral_rolloff.mean(axis=0).mean(axis=0)
        elif self.feature_to_extract is "var": feature = spectral_rolloff.var()
        else: feature = spectral_rolloff.mean(axis=0).mean(axis=0)
        return feature

    def get_spectral_centroid(self, audio_array, sr=None):
        if sr is None: sr=self.sr
        
        spectral_centroids = librosa.feature.spectral_centroid(audio_array, sr=sr)
        
        if self.feature_to_extract is "mean": feature = spectral_centroids.mean(axis=0).mean(axis=0)
        elif self.feature_to_extract is "var": feature = spectral_centroids.var()
        else: feature = spectral_centroids.mean(axis=0).mean(axis=0)
        return feature
    
    # Codigo de prueba 
    def GET_SHOW_spectogram(self, stft, sr=None, hop_length=None):
        if sr is None: sr=self.sr
        if hop_length is None: hop_length=self.hop_length
            
        S = librosa.amplitude_to_db(abs(stft))
        librosa.display.specshow(S, sr=sr, hop_length=hop_length, x_axis='time', y_axis='linear')


In [8]:
# Creating a pandas data frame with features

class MusicFeaturesDictCreator:
    """
    Class aim to create a dictionary with music features, concatenate music feature dictionaries 
    and export a final dictionary to a pandas dataFrame
    """
    
    def __init__(self, features_dictionary=None , number_mfccs=None):
        if features_dictionary is not None:
            self.features_dictionary = features_dictionary
            self.features_dictionary_keys = list(self.features_dictionary.keys())
        else:
            self.features_dictionary = {
                    'Genre': [],
                    'Energy': [],
                    'RMSE': [],
                    'ZCR': [],
                    'MFCCS': number_mfccs,
                    'CQT': [],
                    'Spectral_Contrast': [],
                    'Chromagram':[],
                    'Tempo':[],
                    'Autocorrelation':[],
                    'STFT':[],
                    'Rolloff':[],
                    'Spectral_Centroid':[],
            }
            self.features_dictionary_keys = list(self.features_dictionary.keys())
            

    def ampliate_features_dictionary(self, audios_list, label_name, features_extractor:FeaturesExtractor):
        """
        Make an addition of features extracted from an audio list to the instance dictionary created in the intantiation of the class
        """
        
        for audio_array in audios_list:
                
            self.features_dictionary['Genre'].append(label_name)
                
            if len(self.features_dictionary_keys) > 1:
                short_time_energy = features_extractor.get_short_time_energy(audio_array)
                self.features_dictionary[self.features_dictionary_keys[1]].append(short_time_energy)
                
            if len(self.features_dictionary_keys) > 2:
                rmse = features_extractor.get_rmse(audio_array)
                self.features_dictionary[self.features_dictionary_keys[2]].append(rmse)
                
            if len(self.features_dictionary_keys) > 3:
                zcr = features_extractor.get_zcr(audio_array)
                self.features_dictionary[self.features_dictionary_keys[3]].append(zcr)
            
            if len(self.features_dictionary_keys) > 4:
                number_mfccs = self.features_dictionary['MFCCS']
                mfccs = features_extractor.get_mfccs_means(audio_array, number_mfccs)
                print(mfccs)
                print(mfccs.shape)
                
               # Initializion of mfccs keys if yet it not exist
                if not 'MFCCS0' in self.features_dictionary:
                    for i in range(0, len(mfccs)):
                        self.features_dictionary['MFCCS'+str(i)] = []
                        
                for i in range(0, len(mfccs)):
                    self.features_dictionary['MFCCS'+str(i)].append(mfccs[i])
            
            if len(self.features_dictionary_keys) > 5:
                cqt = features_extractor.get_cqt(audio_array)
                self.features_dictionary[self.features_dictionary_keys[5]].append(cqt)
            
            if len(self.features_dictionary_keys) > 6:
                spectral_contrast = features_extractor.get_spectral_contrast(audio_array)
                self.features_dictionary[self.features_dictionary_keys[6]].append(spectral_contrast)
            
            if len(self.features_dictionary_keys) > 7:
                chromagram = features_extractor.get_chromagram(audio_array)
                self.features_dictionary[self.features_dictionary_keys[7]].append(chromagram)
            
            if len(self.features_dictionary_keys) > 8:
                tempo = librosa.beat.tempo(audio_array, sr=22050)[0]
                self.features_dictionary[self.features_dictionary_keys[8]].append(tempo)
            
            if len(self.features_dictionary_keys) > 9:
                autocorrelation = features_extractor.get_autocorrelation(audio_array)
                self.features_dictionary[self.features_dictionary_keys[9]].append(autocorrelation)
            
            if len(self.features_dictionary_keys) > 10:
                stft = features_extractor.get_stft(audio_array)
                self.features_dictionary[self.features_dictionary_keys[10]].append(stft)
            
            if len(self.features_dictionary_keys) > 11:
                rolloff = features_extractor.get_rolloff(audio_array)
                self.features_dictionary[self.features_dictionary_keys[11]].append(rolloff)
            
            if len(self.features_dictionary_keys) > 12:
                spectral_centroid = features_extractor.get_spectral_centroid(audio_array)
                self.features_dictionary[self.features_dictionary_keys[12]].append(spectral_centroid)
                
        return self.features_dictionary
    
    def concatenate_mfccs_tags(tags_array, number_mfccs=13):
        """
        Method that concatenate mffcs tags in a tags array
        """
        tags_mfccs_columns = ["" for x in range(number_mfccs)]
        mfccs_literal = 'MFCCS'
        for i in range(0, number_mfccs):
            tags_mfccs_columns[i] = 'MFCCS'+str(i)

        tags_array = [*tags_array, *tags_mfccs_columns]
        return tags_array
    
    def concatenate_features_arrays_dictionaries(self, dict_one, dict_two):
    
        dict_two_size = len(dict_two['Energy'])

        for i in range(0, dict_two_size):
            if 'Energy' in self.features_dictionary:
                dict_one['Energy'].append(dict_two['Energy'][i])
            
            if 'RMSE' in self.features_dictionary:
                dict_one['RMSE'].append(dict_two['RMSE'][i])
            
            if 'ZCR' in self.features_dictionary:
                dict_one['ZCR'].append(dict_two['ZCR'][i])
            
#             if 'MFCCS' in self.features_dictionary:
#                 dict_one['MFCCS'].append(dict_two['MFCCS'][i])
            
            if 'CQT' in self.features_dictionary:
                dict_one['CQT'].append(dict_two['CQT'][i])
            
            if 'Spectral_Contrast' in self.features_dictionary:
                dict_one['Spectral_Contrast'].append(dict_two['Spectral_Contrast'][i])
            
            if 'Chromagram' in self.features_dictionary:
                dict_one['Chromagram'].append(dict_two['Chromagram'][i])
            
            if 'Tempo' in self.features_dictionary:
                dict_one['Tempo'].append(dict_two['Tempo'][i])
            
            if 'Autocorrelation' in self.features_dictionary:
                dict_one['Autocorrelation'].append(dict_two['Autocorrelation'][i])
                
            if 'STFT' in self.features_dictionary:
                dict_one['STFT'].append(dict_two['STFT'][i])
            
            if 'Rolloff' in self.features_dictionary:
                dict_one['Rolloff'].append(dict_two['Rolloff'][i])
            
            if 'Spectral_Centroid' in self.features_dictionary:
                dict_one['Spectral_Centroid'].append(dict_two['Spectral_Centroid'][i])
            
        return dict_one
    
    


In [9]:
def multiprocess_feature_dict_creation():
    
    mean_features_extractor = FeaturesExtractor(feature_to_extract="mean")
    var_features_extractor = FeaturesExtractor(feature_to_extract="var")
    
    
    
    mean_features_dictionary = {
                    'Genre': [],
                    'Energy_Mean': [],
                    'RMSE_Mean': [],
                    'ZCR_Mean': [],
                    'MFCCS': 13,
                    'CQT_Mean': [],
                    'Spectral_Contrast_Mean': [],
                    'Chromagram_Mean':[],
                    'Tempo_Mean':[],
                    'Autocorrelation_Mean':[],
                    'STFT_Mean':[],
                    'Rolloff_Mean':[],
                    'Spectral_Centroid_Mean':[],
    }
    
    var_features_dictionary = {
                    'Genre': [],
                    'Energy_Var': [],
                    'RMSE_Var': [],
                    'ZCR_Var': [],
                    'MFCCS': 13,
                    'CQT_Var': [],
                    'Spectral_Contrast_Var': [],
                    'Chromagram_Var':[],
                    'Tempo_Var':[],
                    'Autocorrelation_Var':[],
                    'STFT_Var':[],
                    'Rolloff_Var':[],
                    'Spectral_Centroid_Var':[],
    }
    
    mean_feature_dict_creator = MusicFeaturesDictCreator(mean_features_dictionary)
    var_feature_dict_creator = MusicFeaturesDictCreator(var_features_dictionary)
    
#     LINES USED FOR TESTING RUNNING EXCEPTIONS USING LESS DATA
    
#     mean_features_array_dict = mean_feature_dict_creator.ampliate_features_dictionary(audios_blues[:2], 'Blues', mean_features_extractor) # Initializing
#     mean_features_array_dict = mean_feature_dict_creator.ampliate_features_dictionary(audios_classical[:2], 'Classical', mean_features_extractor)
    
#     var_features_array_dict = var_feature_dict_creator.ampliate_features_dictionary(audios_blues[:2], 'Blues', var_features_extractor) # Initializing
#     var_features_array_dict = var_feature_dict_creator.ampliate_features_dictionary(audios_classical[:2], 'Classical', var_features_extractor)
    
#     features_array_dict = {**mean_features_array_dict, **var_features_array_dict}
    
    
#     GTZAN
    
    
#     mean_features_array_dict = mean_feature_dict_creator.ampliate_features_dictionary(audios_blues, 'Blues', mean_features_extractor) # Initializing
#     mean_features_array_dict = mean_feature_dict_creator.ampliate_features_dictionary(audios_classical, 'Classical', mean_features_extractor)
#     mean_features_array_dict = mean_feature_dict_creator.ampliate_features_dictionary(audios_country, 'Country', mean_features_extractor)
#     mean_features_array_dict = mean_feature_dict_creator.ampliate_features_dictionary(audios_disco, 'Disco', mean_features_extractor)
#     mean_features_array_dict = mean_feature_dict_creator.ampliate_features_dictionary(audios_hiphop, 'Hiphop', mean_features_extractor)
#     mean_features_array_dict = mean_feature_dict_creator.ampliate_features_dictionary(audios_jazz, 'Jazz', mean_features_extractor)
#     mean_features_array_dict = mean_feature_dict_creator.ampliate_features_dictionary(audios_metal, 'Metal', mean_features_extractor)
#     mean_features_array_dict = mean_feature_dict_creator.ampliate_features_dictionary(audios_pop, 'Pop', mean_features_extractor)
#     mean_features_array_dict = mean_feature_dict_creator.ampliate_features_dictionary(audios_reggae, 'Reggae', mean_features_extractor)
#     mean_features_array_dict = mean_feature_dict_creator.ampliate_features_dictionary(audios_rock, 'Rock', mean_features_extractor)
    
#     var_features_array_dict = var_feature_dict_creator.ampliate_features_dictionary(audios_blues, 'Blues', var_features_extractor) # Initializing
#     var_features_array_dict = var_feature_dict_creator.ampliate_features_dictionary(audios_classical, 'Classical', var_features_extractor)
#     var_features_array_dict = var_feature_dict_creator.ampliate_features_dictionary(audios_country, 'Country', var_features_extractor)
#     var_features_array_dict = var_feature_dict_creator.ampliate_features_dictionary(audios_disco, 'Disco', var_features_extractor)
#     var_features_array_dict = var_feature_dict_creator.ampliate_features_dictionary(audios_hiphop, 'Hiphop', var_features_extractor)
#     var_features_array_dict = var_feature_dict_creator.ampliate_features_dictionary(audios_jazz, 'Jazz', var_features_extractor)
#     var_features_array_dict = var_feature_dict_creator.ampliate_features_dictionary(audios_metal, 'Metal', var_features_extractor)
#     var_features_array_dict = var_feature_dict_creator.ampliate_features_dictionary(audios_pop, 'Pop', var_features_extractor)
#     var_features_array_dict = var_feature_dict_creator.ampliate_features_dictionary(audios_reggae, 'Reggae', var_features_extractor)
#     var_features_array_dict = var_feature_dict_creator.ampliate_features_dictionary(audios_rock, 'Rock', var_features_extractor)


# ISMIR04

    mean_features_array_dict = mean_feature_dict_creator.ampliate_features_dictionary(audios_classical, 'Classical', mean_features_extractor)
    mean_features_array_dict = mean_feature_dict_creator.ampliate_features_dictionary(audios_electronic, 'Electronic', mean_features_extractor)
    mean_features_array_dict = mean_feature_dict_creator.ampliate_features_dictionary(audios_jazz, 'Jazz', mean_features_extractor)
    mean_features_array_dict = mean_feature_dict_creator.ampliate_features_dictionary(audios_metal, 'Metal', mean_features_extractor)
    mean_features_array_dict = mean_feature_dict_creator.ampliate_features_dictionary(audios_pop, 'Pop', mean_features_extractor)
    mean_features_array_dict = mean_feature_dict_creator.ampliate_features_dictionary(audios_punk, 'Punk', mean_features_extractor)
    mean_features_array_dict = mean_feature_dict_creator.ampliate_features_dictionary(audios_rock, 'Rock', mean_features_extractor)
    mean_features_array_dict = mean_feature_dict_creator.ampliate_features_dictionary(audios_world, 'World', mean_features_extractor)

    var_features_array_dict = var_feature_dict_creator.ampliate_features_dictionary(audios_classical, 'Classical', var_features_extractor)
    var_features_array_dict = var_feature_dict_creator.ampliate_features_dictionary(audios_electronic, 'Electronic', var_features_extractor)
    var_features_array_dict = var_feature_dict_creator.ampliate_features_dictionary(audios_jazz, 'Jazz', var_features_extractor)
    var_features_array_dict = var_feature_dict_creator.ampliate_features_dictionary(audios_metal, 'Metal', var_features_extractor)
    var_features_array_dict = var_feature_dict_creator.ampliate_features_dictionary(audios_pop, 'Pop', var_features_extractor)
    var_features_array_dict = var_feature_dict_creator.ampliate_features_dictionary(audios_punk, 'Punk', var_features_extractor)
    var_features_array_dict = var_feature_dict_creator.ampliate_features_dictionary(audios_rock, 'Rock', var_features_extractor)
    var_features_array_dict = var_feature_dict_creator.ampliate_features_dictionary(audios_world, 'World', var_features_extractor)


    features_array_dict = {**mean_features_array_dict, **var_features_array_dict}
#     features_array_dict = mean_features_array_dict
#     features_array_dict = var_features_array_dict

    return features_array_dict

def df_extraction():
    """
    Method that convert a features dictionary in a pandas dataFrame
    """
    
    features_array_dict = multiprocess_feature_dict_creation()
    
    
#     tags_dataframe_columns = ['Genre', 'Energy_Mean', 'RMSE_Mean', 'ZCR_Mean', 'CQT_Mean', 'Spectral_Contrast_Mean', 'Chromagram_Mean', 'Tempo_Mean', 'STFT_Mean', 
#                               'Autocorrelation_Mean', 'STFT_Mean', 'Spectral_Centroid_Mean', 'Rolloff_Mean']
    
    tags_dataframe_columns = ['Genre', 'Energy_Mean', 'RMSE_Mean', 'ZCR_Mean', 'CQT_Mean', 'Spectral_Contrast_Mean', 'Chromagram_Mean', 'Tempo_Mean', 'STFT_Mean', 
                              'Autocorrelation_Mean', 'STFT_Mean', 'Spectral_Centroid_Mean', 'Rolloff_Mean',
                              'Energy_Var', 'RMSE_Var', 'ZCR_Var', 'CQT_Var', 'Spectral_Contrast_Var', 'Chromagram_Var', 'Tempo_Var', 'STFT_Var',
                              'Autocorrelation_Var', 'STFT_Var', 'Spectral_Centroid_Var', 'Rolloff_Var']
    
    tags_dataframe_columns = MusicFeaturesDictCreator.concatenate_mfccs_tags(tags_dataframe_columns)
    print(tags_dataframe_columns)
#     tags_dataframe_columns = ['Genre', 'Energy', 'RMSE', 'ZCR', 'CQT', 'Spectral_Contrast', 'Chromagram', 'Tempo', 'MFCCS']
    
    print(features_array_dict)
    
    df = pd.DataFrame(features_array_dict, columns = tags_dataframe_columns)
    
    return df

# Export pandas dataFrame in a csv

df = df_extraction()

df.to_csv('ismir04_100.csv')


print(df.head(5))
print('impresito')

[101 152  20  31  -1  19  -6  17  -2  14 -10   8  -5]
(13,)
[ 32 154  31  32   9  20  -3   6  -3   9  -4   0  -7]
(13,)
[ 63 137  31  35  -3  22  -1  14 -13  10 -10   6 -10]
(13,)
[-151  105   48   45   28   25   10   12    8   12    6    8    6]
(13,)
[-213   70   26   31   15   19    9   11    4    8    3    4    2]
(13,)
[-136  115   46   47   29   27   12   15    6   11    4    7   -1]
(13,)
[-60 155  61  45  24  26  11   8   0   5  -3   7  -3]
(13,)
[-120  114   52   48   26   28   12   15    6   11    3    2   -2]
(13,)
[-163   87   48   40   30   24   18   18   17   15   11   10    7]
(13,)
[-134  112   42   41   20   30   10   16    5   13    6    6    0]
(13,)
[-97 140  58  40  26  28  11   8   2   4   1  -1  -7]
(13,)
[-154  128   60   51   29   32   16   15    9   12    4    7    3]
(13,)
[-118  124   58   43   26   15    7    8    4    5    2    2    1]
(13,)
[-162  174   96   42   16    8    7    6    2   -2   -1    1    0]
(13,)
[-179   95   53   44   31   25   18   16   

In [5]:
 feature_dict_creator = MusicFeaturesDictCreator()
    
print(feature_dict_creator.features_dictionary)

{'Genre': [], 'Energy': [], 'RMSE': [], 'ZCR': [], 'MFCCS': None, 'CQT': [], 'Spectral_Contrast': [], 'Chromagram': [], 'Tempo': [], 'Autocorrelation': [], 'STFT': [], 'Rolloff': [], 'Spectral_Centroid': []}
